services:
  catalogservice:
    build:
      context: .
      dockerfile: catalogService/Dockerfile
    environment:
      - PORT=:8080
      - DB_HOST=${DB_ADDRESS}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SCHEMA=catalog
    restart: unless-stopped
    ports:
      - 8080:8080

  backgroundworkerservice:
    build:
      context: .
      dockerfile: backgroundWorkerService/Dockerfile
    environment:
      - PORT=:8080
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_TTL=${REDIS_TTL}
      - FIXER_TOKEN=${FIXER_TOKEN}
    restart: unless-stopped
    ports:
      - 8082:8080

  postgresql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  postgresql_data:
    driver: local