services:
  catalog_service:
    build: ./catalogService
    environment:
      - USER_DB=${USER_DB}
      - PASSWORD_DB=${PASSWORD_DB}
      - HOST_DB=${HOST_DB}
      - PORT_DB=${PORT_DB}
    restart: unless-stopped
    ports:
      - 8080:8080

  postgresql:
    image: docker.io/bitnami/postgresql:17
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local